# Generated by Django 4.2.4 on 2024-01-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userkill_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userkill',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], default=0),
        ),
    ]
